version: '2'
services:
  zookeeper:
    # Offical Apache ZooKeeper image. See https://hub.docker.com/_/zookeeper/
    image: zookeeper:3.4.9

  kafka:
    build: .
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
